# 메트릭 서버 설치
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: member-hpa
  namespace: soldesk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: member-depl
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
